# <span style="color:blue"> Numpy - Basics </span>
### Exercise 00: Creating a numpy array using arange

In [2]:
import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 01: Extract elements from an array

- Declare and initialize an array as done below:
    * arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Then, extract all odd numbers from arr to achieve the desired output.
    * Desired output:
    [1 3 5 7 9]

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr = np.array([],dtype=int)

for num in arr:
    if num % 2 != 0:
        new_arr = np.insert(new_arr, len(new_arr), num)
print(new_arr)

[1 3 5 7 9]


### Exercise 02: Converting a one-dimensional array to two-dimensional

- Declare and initialize an array as done below
    * np.arange(10)

- Try recreating this output:

    [[0 1 2 3 4]
    
    [5 6 7 8 9]]

In [5]:
arr = np.arange(10).reshape(2,5)
print(arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 03: Inspecting a numpy array

- Create a 2d array with 3 rows and 4 columns
- Inspect its shape, datatype, size, number dimensions

In [ ]:
myList = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]

# shape

# datatype

# size

# number dimensions
