# <span style="color:blue"> **Numpy - Basics** </span>
### Exercise 00: Creating a numpy array using arange

In [30]:
import numpy as np

# arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. 
# The interval mentioned is half opened i.e. [Start, Stop)

a = np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


### Exercise 01: Extract elements from an array

- Declare and initialize an array as done below:
    * arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Then, extract all odd numbers from arr to achieve the desired output.
    * Desired output:
    [1 3 5 7 9]

In [29]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr = np.array([],dtype=int)

for num in arr:
    if num % 2 != 0:
        new_arr = np.insert(new_arr, len(new_arr), num)
print(new_arr)

[1 3 5 7 9]


### Exercise 02: Converting a one-dimensional array to two-dimensional

- Declare and initialize an array as done below
    * np.arange(10)

- Try recreating this output:

    [[0 1 2 3 4]
    
    [5 6 7 8 9]]

In [31]:
# numpy.reshape(array, shape, order = ‘C’) : shapes an array without changing data of array.

arr = np.arange(10).reshape(2,5)
print(arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 03: Inspecting a numpy array

- Create a 2d array with 3 rows and 4 columns
- Inspect its shape, datatype, size, number dimensions

In [32]:
myList = np.array([[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]])

# Shape: Gives an idea of how many (rows, columns) are there in a given array.
print("Shape:", myList.shape)

# Data type:  To get the data type of the array.
print("dtype:", myList.dtype)

# Size: To get the size of the array in ‘kB’.
print("Size:", myList.itemsize)

# Number dimensions: To get the dimensionality of the array.
print("Dimensions:", myList.ndim)

Shape: (3, 4)
dtype: int64
Size: 8
Dimensions: 2


### Exercise 04: Stack them (arrays) up!

- Stack the arrays a and b vertically

  * a = np.arange(10).reshape(2,-1)
  * b = np.repeat(1, 10).reshape(2,-1)

- Try creating this output:

  [[0 1 2 3 4]

  [5 6 7 8 9]

  [1 1 1 1 1]
  
  [1 1 1 1 1]]

In [33]:
a = np.arange(10).reshape(2,-1)
print("1st Input array : \n", a, "\n")  

b = np.repeat(1, 10).reshape(2,-1)
print("2nd Input array : \n", b, "\n")  

#numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.
# Stacking the two arrays vertically 

out_arr = np.vstack((a,b))
print("Output vertically stacked array:\n", out_arr) 

1st Input array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

2nd Input array : 
 [[1 1 1 1 1]
 [1 1 1 1 1]] 

Output vertically stacked array:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 05: Replacing missing value

  myList = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]

  arr = np.array(myList, dtype='float')

  arr[1,1] = np.nan # not a number

  arr[1,2] = np.inf # infinite

  print(arr)

* Output:

  [[ 1. 2. 3. 4.]

  [ 3. -1. -1. 6.]

  [ 5. 6. 7. 8.]]

In [56]:
myList = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr = np.array(myList, dtype='float')
arr[1,1] = np.nan # not a number
arr[1,2] = np.inf # infinite
print(arr, "\n")

# find indices where nan and inf value are present 
indNan = np.where(np.isnan(arr))
indInf = np.where(np.isinf(arr))

# replace inds with a value
arr[indNan] = -1
arr[indInf] = -1

# printing final array 
print ("Final array \n", arr) 


[[ 1.  2.  3.  4.]
 [ 3. nan inf  6.]
 [ 5.  6.  7.  8.]] 

Final array 
 [[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]


### Exercise 06: Drop all missing values from a numpy array

np.array([1,2,3,np.nan,5,6,7,np.nan])

- Output:

  [ 1. 2. 3. 5. 6. 7.]

In [65]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
print("Original array: \n", arr, "\n") 

arr = arr[~np.isnan(arr)]
print("Dropped missing values in the array: \n", arr, "\n")

# Explanation:
# The inner function, numpy.isnan returns a boolean/logical array which has the value True everywhere that x is not-a-number. 
# As we want the opposite, we use the logical-not operator, ~ to get an array with Trues everywhere that x is a valid number.
# Lastly we use this logical array to index into the original array x, to retrieve just the non-NaN values.


Original array: 
 [ 1.  2.  3. nan  5.  6.  7. nan] 

Dropped missing values in the array: 
 [1. 2. 3. 5. 6. 7.] 



### Exercise 07: Find duplicate records in a numpy array

- Stack the arrays a and b vertically

      np.random.seed(100)

      a = np.random.randint(0, 5, 10)

      print('Array: ', a)


Mark the unique position as false:

Output:

[False True False True False False True True True True]

In [93]:
a = np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: \n', a , "\n")

# Create All True Array
output = np.full(a.shape[0], True)        

# Find Unique Elements
uniques = np.unique(a, return_index=True)[1]   

# Return value: The indices of the first occurrences of the unique values in the original array. 
# Only provided if return_index is True.
print("Indeces of Unique values:\n",uniques , "\n")

# Mark Them as False
output[uniques] = False  

print("Output: \n", output , "\n")

Array: 
 [0 0 3 0 2 4 2 2 2 2] 

Indeces of Unique values:
 [0 4 2 5] 

Output: 
 [False  True False  True False False  True  True  True  True] 

